# Generated by Django 4.1.7 on 2023-03-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('texto_nota', models.CharField(max_length=300)),
                ('link_nota_original', models.CharField(max_length=300)),
                ('link_imagen', models.CharField(max_length=300)),
                ('creacion', models.DateTimeField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipalidad_o_Localidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paginas_Oficiales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('link_pagina', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_de_Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.actividades')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.categorias')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='id_municipio_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.municipalidad_o_localidad'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='id_pagina_oficial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.paginas_oficiales'),
        ),
    ]
